steps:
  debug:
    image: alpine
    commands:
      - echo "DEBUG: DOCKERHUB_USERNAME=$${DOCKERHUB_USERNAME}"
      - echo "DEBUG: CI_REPO_NAME=$${CI_REPO_NAME}"
    environment:
      DOCKERHUB_USERNAME:
        from_secret: dockerhub_username
    when:
      branch: main
      event: push

  publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: mzezin123/${CI_REPO_NAME}
      tags: latest
      cache: true
      skip_tls_verify: false
      build_args:
        - COMMIT_SHA=${CI_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
    when:
      branch: main
      event: push