steps:
- name: publish
  image: woodpeckerci/plugin-kaniko
  settings:
    repo: ${DOCKERHUB_USERNAME}/{CI_REPO_NAME}
    tags: ${CI_COMMIT_SHA}, latest
    cache: true
    skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
    build_args:
    - COMMIT_SHA=${CI_COMMIT_SHA}
    - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
    username:
      from_secret: docker-username
    password:
      from_secret: docker-password
      environment:
      DOCKERHUB_USERNAME:
        from_secret: dockerhub_username
      DOCKERHUB_TOKEN:
        from_secret: dockerhub_token
    when:
      branch: main
      event: push