steps:
- name: publish
  image: woodpeckerci/plugin-kaniko
  settings:
    repo: mzezin123/${CI_REPO_NAME}
    tags: latest
    cache: true
    skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
    build_args:
    - COMMIT_SHA=${CI_COMMIT_SHA}
    - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_token
  environment:
    DOCKERHUB_USERNAME:
      from_secret: dockerhub_username
    DOCKERHUB_TOKEN:
      from_secret: dockerhub_token
    when:
      branch: main
      event: push