steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: mzezin123/${CI_REPO_NAME}
      tag: latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
    when:
      branch: main
      event: push