steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: mzezin123/${CI_REPO_NAME}
      tags: latest
      platforms: linux/amd64,linux/arm64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
    when:
      branch: main
      event: push